<?php
$allPosts = [
  [
    "title" => "Who is Leo Koguan, the Elon fanboy and one of Tesla's largest shareholders who last year that Musk had 'abandoned' the EV maker",
    "author" => "Aol Staff",
    "published_date" => "2023-12-30 17:51:00",
    "published_date_precision" => "full",
    "link" => "https://www.aol.com/lee-koguan-elon-fanboy-one-133000085.html",
    "clean_url" => "aol.com",
    "summary" => "Elon Musk and Leo KoGuan Getty\n\nLeo KoGuan is a major Tesla shareholder and regularly touts his big buying sprees of the stock.\n\nBut the one-time, self-proclaimed Elon Musk \"fanboy\" has since soured on his leadership.\n\n\"Elon abandoned Tesla and Tesla has no working CEO,\" KoGuan tweeted in December 2022. \"Tesla needs and deserves to have working full time CEO.\"\n\nLeo KoGuan is perhaps best known as an Elon Musk \"fanboy,\" who built a massive stake in Tesla during the pandemic and consistently fires off tweetstorms about the EV maker.",
    "rights" => "aol.com",
    "rank" => 152,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "AOL Staff,At Am,Brian Evans",
    "media" => "https://media.zenfs.com/en/aol_business_insider_articles_308/436cea7e316f2e7e1b03064a1b655ee1",
    "is_opinion" => false,
    "twitter_account" => "@AOL",
    "_score" => 23.926832,
    "_id" => "aca3d4776e5de00d1ee9541718ed7262"
  ],
  [
    "title" => "Transcript: Was Musk's 2023 ‘Explosive,' ‘Hysterical,' ‘Unstable' or ‘Great?'",
    "author" => "Tiffany Tsoi",
    "published_date" => "2023-12-27 13:47:11",
    "published_date_precision" => "full",
    "link" => "https://www.bloomberg.com/news/articles/2023-12-27/transcript-was-musk-s-2023-explosive-hysterical-unstable-or-great",
    "clean_url" => "bloomberg.com",
    "summary" => "By\n\nSave\n\nIn this week's episode of Elon, Inc., we evaluate the year that Elon Musk has had. For better or worse, 2023 was the year of Elon — you can say a lot about what Musk has said and done, but no one would argue he's been marginalized. He has put himself in the center of the news and managed to stabilize his business empire, despite his amplification of right wing conspiracy theories, endorsement of antisemitism, and suggestion that the chief executive of one of the world's most beloved companies 'go f— yourself.",
    "rights" => "bloomberg.com",
    "rank" => 92,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Tiffany Tsoi",
    "media" => "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iez0ES3jFTmk/v1/1200x800.jpg",
    "is_opinion" => false,
    "twitter_account" => null,
    "_score" => 23.639435,
    "_id" => "147c621437a6edad27a96f99da49a35a"
  ],
  [
    "title" => "Elon Musk trolled his way through 2023. He's still ending the year $100 billion up.",
    "author" => "Tom Carter",
    "published_date" => "2023-12-27 16:52:25",
    "published_date_precision" => "full",
    "link" => "https://www.businessinsider.com/elon-musk-was-2023-biggest-troll-hes-still-100b-richer-2023-12",
    "clean_url" => "businessinsider.com",
    "summary" => "Elon Musk has gone from crisis to crisis this year. Somehow he's nearly $100 billion richer.",
    "rights" => "Insider Inc. 2023",
    "rank" => 106,
    "topic" => "business",
    "country" => "US",
    "language" => "en",
    "authors" => "Tom Carter",
    "media" => "https://i.insider.com/658c475c1c5c7b8c9a0c3734?width=1200&format=jpeg",
    "is_opinion" => false,
    "twitter_account" => null,
    "_score" => 23.624687,
    "_id" => "b6ee6e727f794973f0bc4189f7862ef7"
  ],
  [
    "title" => "Elon Musk, X and the Problem of Misinformation in an Era Without Trust",
    "author" => "",
    "published_date" => "2023-12-31 10:01:01",
    "published_date_precision" => "full",
    "link" => "https://www.nytimes.com/2023/12/31/books/review/elon-musk-trust-misinformation-disinformation.html",
    "clean_url" => "nytimes.com",
    "summary" => "Elon Musk thinks a free market of ideas will self-correct. Liberals want to regulate it. Both are missing a deeper predicament.",
    "rights" => "Copyright 2023 The New York Times Company",
    "rank" => 40,
    "topic" => "entertainment",
    "country" => "US",
    "language" => "en",
    "authors" => "",
    "media" => "",
    "is_opinion" => false,
    "twitter_account" => null,
    "_score" => 23.601717,
    "_id" => "5aa1498efc3de37cd3aee7b4f10e24d7"
  ],
  [
    "title" => "Who is Leo Koguan, the Elon fanboy and one of Tesla's largest shareholders who last year that Musk had 'abandoned' the EV maker",
    "author" => "Brian Evans",
    "published_date" => "2023-12-30 17:51:00",
    "published_date_precision" => "full",
    "link" => "https://news.yahoo.com/lee-koguan-elon-fanboy-one-133000898.html",
    "clean_url" => "yahoo.com",
    "summary" => "Leo KoGuan is a major Tesla shareholder and regularly touts his big buying sprees of the stock.\nBut the one-time, self-proclaimed Elon Musk \"fanboy\" has since soured on his leadership.\n\"Elon abandoned Tesla and Tesla has no working CEO,\" KoGuan tweeted in December 2022. \"Tesla needs and deserves to have working full time CEO.\"\nLeo KoGuan is perhaps best known as an Elon Musk \"fanboy,\" who built a massive stake in Tesla during the pandemic and consistently fires off tweetstorms about the EV maker.",
    "rights" => "yahoo.com",
    "rank" => 31,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Brian Evans",
    "media" => "https://media.zenfs.com/en/insider_articles_922/436cea7e316f2e7e1b03064a1b655ee1",
    "is_opinion" => false,
    "twitter_account" => "@YahooNews",
    "_score" => 23.590126,
    "_id" => "e1411e514204cfd5765c2dd1c583c864"
  ],
  [
    "title" => "Artificial intelligence, Elon Musk and the biggest tech stories of 2023",
    "author" => "CBS News",
    "published_date" => "2023-12-28 00:33:00",
    "published_date_precision" => "full",
    "link" => "https://www.cbsnews.com/video/ai-elon-musk-2023-biggest-tech-stories",
    "clean_url" => "cbsnews.com",
    "summary" => "Artificial intelligence, Elon Musk and the biggest tech stories of 2023 From the rise of artificial intelligence to Elon Musk's rebranding of Twitter, 2023 saw major changes in the tech industry. CBS News senior business and tech correspondent Jo Ling Kent joins to look back at the year in tech -- and to discuss where the industry is headed in 2024.",
    "rights" => "cbsnews.com",
    "rank" => 204,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "CBS News,Paramount Global",
    "media" => "https://assets3.cbsnewsstatic.com/hub/i/r/2023/12/28/6f57bfa9-5652-4142-bf76-2905cd0dd9cd/thumbnail/1200x630/dd7a8981a3ae8437639ca82c06083877/cbsn-fusion-ai-elon-musk-2023-biggest-tech-stories-thumbnail.jpg?v=5382e209c94ee904b3a96a69f8ca0ce0",
    "is_opinion" => false,
    "twitter_account" => "@CBSNews",
    "_score" => 23.55929,
    "_id" => "8ef74a054c1f8f4a4d56afb5bc0562aa"
  ],
  [
    "title" => "New Republic slaps 'Scoundrel of the Year' title on X owner Elon Musk, calls him ‘evil', 'deeply hateful'",
    "author" => "HT Tech",
    "published_date" => "2023-12-29 12:17:50",
    "published_date_precision" => "full",
    "link" => "https://tech.hindustantimes.com/tech/news/new-republic-slaps-scoundrel-of-the-year-title-on-x-owner-elon-musk-calls-him-evil-deeply-hateful-71703852004095.html",
    "clean_url" => "hindustantimes.com",
    "summary" => "In a shocking development, the American magazine, the New Republic has crowned X owner Elon Musk as ‘The Scoundrel of the Year'. In a long article liberally seeded with choice name-calling, the magazine charted out the actions and decisions made by the billionaire in 2023 that got his this dubious award. The New Republic said, 'He proved this year that he's not just evil but deeply stupid too'. This comes after Musk made the headlines recently for posting anti-semitic comments on X, which led to multiple advertisers boycotting the platform and also using expletives during a live interview.",
    "rights" => "hindustantimes.com",
    "rank" => 980,
    "topic" => "tech",
    "country" => "IN",
    "language" => "en",
    "authors" => "HT Tech",
    "media" => "https://images.hindustantimes.com/tech/img/2023/12/29/1600x900/Elon_musk_1698723110118_1703852038746.JPG",
    "is_opinion" => false,
    "twitter_account" => "@HTTech",
    "_score" => 23.552824,
    "_id" => "aeb32abb1fd65387c01f3edfa4cad669"
  ],
  [
    "title" => "‘He's my son, not Zeus' Elon Musk's dad Errol looks back on relationship after being portrayed as villain in CEO's book",
    "author" => "Alex Diaz",
    "published_date" => "2023-12-31 22:00:06",
    "published_date_precision" => "full",
    "link" => "https://www.thesun.co.uk/news/25212173/elon-musks-dad-errol-rollercoaster-year-relationship",
    "clean_url" => "thesun.co.uk",
    "summary" => "FAMILY MATTERS ‘He's my son, not Zeus' Elon Musk's dad Errol looks back on relationship after being portrayed as villain in CEO's book\n\nELON Musk's dad has looked back on a rollercoaster year that saw the pair air their differences before reuniting for the first time in seven years.\n\nRetired electromechanical engineer Errol, 77, revealed that he met with three of his young grandchildren for the first time when he linked up with Elon at a SpaceX launch in Texas last month.\n\n8 Elon Musk is seen at an even in New York in November Credit: Getty\n\n8 Errol Musk poses for a portrait at his house in Langebaan, South Africa, in May 2022 Credit: AFP\n\n8 A young Elon Musk smiles for the camera in a pic from the family photo album Credit: Errol Musk\n\nThe surprise reunion came after the pair had publicly expressed several points of contention between them throughout 2023.",
    "rights" => "thesun.co.uk",
    "rank" => 442,
    "topic" => "news",
    "country" => "GB",
    "language" => "en",
    "authors" => "Alex Diaz",
    "media" => "https://www.thesun.co.uk/wp-content/uploads/2024/01/esc-elon-musk-dad-off-platform-copy.jpg?strip=all&quality=100&w=1920&h=1080&crop=1",
    "is_opinion" => false,
    "twitter_account" => "@thesun",
    "_score" => 23.362793,
    "_id" => "8b9cb12ff2fa01d7ca398ebcec400f76"
  ],
  [
    "title" => "Who is Leo Koguan, the Elon fanboy and one of Tesla's largest shareholders who last year that Musk had 'abandoned' the EV maker",
    "author" => "Brian Evans",
    "published_date" => "2023-12-30 17:51:00",
    "published_date_precision" => "full",
    "link" => "https://markets.businessinsider.com/news/stocks/tesla-stock-outlook-leo-koguan-elon-musk-shi-international-trading-2023-1",
    "clean_url" => "businessinsider.com",
    "summary" => "Leo KoGuan is a major Tesla shareholder and regularly touts his big buying sprees of the stock.\n\nBut the one-time, self-proclaimed Elon Musk \"fanboy\" has since soured on his leadership.\n\n\"Elon abandoned Tesla and Tesla has no working CEO,\" KoGuan tweeted in December 2022. \"Tesla needs and deserves to have working full time CEO.\"\n\nNEW LOOK Sign up to get the inside scoop on today's biggest stories in markets, tech, and business — delivered daily. Read preview Thanks for signing up! Access your favorite topics in a personalized feed while you're on the go.",
    "rights" => "businessinsider.com",
    "rank" => 106,
    "topic" => "finance",
    "country" => "US",
    "language" => "en",
    "authors" => "Brian Evans",
    "media" => "https://i.insider.com/63c1702133ffb700180f988a?width=1200&format=jpeg",
    "is_opinion" => false,
    "twitter_account" => null,
    "_score" => 23.359457,
    "_id" => "be75c316233470399fc7f92fba2f64c6"
  ],
  [
    "title" => "Elon Musk rebukes media reports on robot \"attack\" in Tesla factory",
    "author" => "",
    "published_date" => "2023-12-28 14:40:29",
    "published_date_precision" => "full",
    "link" => "https://economictimes.indiatimes.com/news/international/us/elon-musk-rebukes-media-reports-on-robot-attack-in-tesla-factory/articleshow/106356545.cms",
    "clean_url" => "indiatimes.com",
    "summary" => "Elon Musk rebuked media reports linking a 2021 factory robot incident to Tesla's Optimus robots, clarifying it involved a Kuka arm. The incident, covered by outlets like Daily Mail and The Information, saw an engineer injured during software updates. Musk defended Optimus robots, expressing hopes for an abundant future. Tesla's safety practices faced scrutiny previously, with concerns in California and China. Representatives from Tesla and Kuka haven't responded to Business Insider's queries. Musk's criticism highlights Tesla's robotics focus amid persistent safety concerns.",
    "rights" => "Copyright:(C) 2023 Bennett Coleman and Co. Ltd, http://info.indiatimes.com/terms/tou.html",
    "rank" => 296,
    "topic" => "economics",
    "country" => "IN",
    "language" => "en",
    "authors" => "",
    "media" => "https://img.etimg.com/thumb/msid-106356541,width-1200,height-630,imgsize-109988,overlay-economictimes/photo.jpg",
    "is_opinion" => false,
    "twitter_account" => "@EconomicTimes",
    "_score" => 23.199617,
    "_id" => "098b4126d2e55c26b72cb35834908ecc"
  ],
  [
    "title" => "'Wrong Frame Of Reference:' Elon Musk Rebuts Tesla Bear For Saying EV Stock Is 'Egregiously Overvalued' Through Toyota Lens",
    "author" => "",
    "published_date" => "2023-12-28 09:46:07",
    "published_date_precision" => "full",
    "link" => "https://www.nasdaq.com/articles/wrong-frame-of-reference:-elon-musk-rebuts-tesla-bear-for-saying-ev-stock-is-egregiously",
    "clean_url" => "nasdaq.com",
    "summary" => "Roth MKM senior research analyst and Tesla Inc (NASDAQ:TSLA) bear, Craig Irwin, is of the opinion that the stock is 'egregiously overvalued,' asserting that the EV giant offers nothing that Japanese automaker Toyota does not. Tesla CEO Elon Musk, ...",
    "rights" => null,
    "rank" => 713,
    "topic" => "finance",
    "country" => "US",
    "language" => "en",
    "authors" => "",
    "media" => null,
    "is_opinion" => false,
    "twitter_account" => null,
    "_score" => 23.084324,
    "_id" => "dee83fae89e5dad24430b99b8f87e9c2"
  ],
  [
    "title" => "Elon Musk is shaping up to be this generation's Henry Ford – for better or worse",
    "author" => "AOL Staff",
    "published_date" => "2023-12-26 11:20:01",
    "published_date_precision" => "full",
    "link" => "https://www.aol.com/elon-musk-shaping-generations-henry-112001793.html",
    "clean_url" => "aol.com",
    "summary" => "Tesla CEO Elon Musk and Ford founder Henry Ford\nHenry Guttmann Collection/Hulton Archive/Getty Images and Slaven Vlasic/Getty Images for The New York Times\nElon Musk and Henry Ford share a lot of similarities.\nBoth men have revolutionized the automotive industry.\nThey also both love stoking public controversy.\nOne hundred years after Henry Ford reshaped the automotive industry with the assembly line, Tesla CEO \nElon Musk\n is doing much the same for electric cars.\nMusk is a once-in-a-generation figure whose \nlegacy is becoming complicated\n in real time – not unlike the Ford founder who revolutionized vehicle production.",
    "rights" => "aol.com",
    "rank" => 152,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "AOL Staff,At Am,Grace Kay,Nora Naughton,Nora Naughton Grace Kay",
    "media" => "https://s.yimg.com/ny/api/res/1.2/yA450Ej6qfxg5I9QfmODHQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA-/https://media.zenfs.com/en/aol_business_insider_articles_308/f5d80144e62188113c65c2868f1a238f",
    "is_opinion" => false,
    "twitter_account" => "@AOL",
    "_score" => 23.077587,
    "_id" => "a78a0bf04924f7b4ce516df69def6c94"
  ],
  [
    "title" => "Elon Musk and Italy's Giorgia Meloni Form a Trans-Atlantic Bond",
    "author" => "Eric Sylvers",
    "published_date" => "2023-12-29 09:53:00",
    "published_date_precision" => "full",
    "link" => "https://www.wsj.com/tech/elon-musk-and-italys-giorgia-meloni-form-a-trans-atlantic-bond-228ffb16?mod=hp_lead_pos10",
    "clean_url" => "wsj.com",
    "summary" => "Elon Musk and Italian Prime Minister Giorgia Meloni have formed one of 2023's more unlikely trans-Atlantic alliances.\n\nBehind their budding friendship lie common interests in political issues such as immigration and demographics, as well as in tech-sector regulation and the risks associated with artificial intelligence.",
    "rights" => "wsj.com",
    "rank" => 89,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Eric Sylvers,Margherita Stancati",
    "media" => "https://images.wsj.net/im-903962/social",
    "is_opinion" => false,
    "twitter_account" => "@WSJ",
    "_score" => 23.042048,
    "_id" => "1c5d71c6e14a9607011ba9e037fffcdf"
  ],
  [
    "title" => "Our Blind Faith in Driverless Cars Knows No Limits",
    "author" => "Stephen Mihm",
    "published_date" => "2023-12-27 15:00:10",
    "published_date_precision" => "full",
    "link" => "https://www.bloomberg.com/opinion/articles/2023-12-27/our-blind-faith-in-driverless-cars-knows-no-limits",
    "clean_url" => "bloomberg.com",
    "summary" => "Visionaries like Elon Musk have been promoting the idea for almost a hundred years. And yet, it never arrives — for obvious reasons.\n\nSave\n\nElon Musk, who had claimed that driverless cars would arrive this year, just got pulled over by federal regulators. Officials from the National Highway Traffic Safety Administration concluded that safety features in Tesla Inc.'s Autopilot system didn't work as designed and nudged the automaker to recall all its vehicles to address the issue.\n\nIt's debatable whether Tesla and Chief Executive Officer Musk can fix the problem, which has more to do with human drivers putting too much faith in the technology.",
    "rights" => "bloomberg.com",
    "rank" => 92,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "A Crash Course In The Future,A Professor,Crisis Economics,Stephen Mihm",
    "media" => "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/i7e0oixEUWn0/v1/1200x909.jpg",
    "is_opinion" => true,
    "twitter_account" => "@opinion",
    "_score" => 22.892881,
    "_id" => "130a9b0ee9accf4a92f9d4d0ef0faae7"
  ],
  [
    "title" => "Elon Musk is shaping up to be this generation's Henry Ford – for better or worse",
    "author" => "Nora Naughton",
    "published_date" => "2023-12-26 13:28:52",
    "published_date_precision" => "full",
    "link" => "https://news.yahoo.com/elon-musk-shaping-generations-henry-112001698.html",
    "clean_url" => "yahoo.com",
    "summary" => "Elon Musk and Henry Ford share a lot of similarities.\nBoth men have revolutionized the automotive industry.\nThey also both love stoking public controversy.\nOne hundred years after Henry Ford reshaped the automotive industry with the assembly line, Tesla CEO Elon Musk is doing much the same for electric cars.\nMusk is a once-in-a-generation figure whose legacy is becoming complicated in real time – not unlike the Ford founder who revolutionized vehicle production.\nMusk and Ford have been compared to one another for several years now.",
    "rights" => "yahoo.com",
    "rank" => 31,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Grace Kay,Nora Naughton,Nora Naughton Grace Kay",
    "media" => "https://s.yimg.com/ny/api/res/1.2/cq7Vq14zRLDZbIzCar_mJQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MDA-/https://media.zenfs.com/en/business_insider_articles_888/f5d80144e62188113c65c2868f1a238f",
    "is_opinion" => false,
    "twitter_account" => "@YahooNews",
    "_score" => 22.891068,
    "_id" => "881a26bf932549f83ecc96fb90819f48"
  ],
  [
    "title" => "Musk Went to Court After Grimes Allegedly Took Two Kids to California",
    "author" => "Noah Kirsch",
    "published_date" => "2023-12-29 18:18:41",
    "published_date_precision" => "full",
    "link" => "https://www.thedailybeast.com/elon-musk-went-to-court-after-grimes-allegedly-took-two-of-their-kids-to-california",
    "clean_url" => "thedailybeast.com",
    "summary" => "Elon Musk's messy split from Canadian musician Grimes continues to make headlines. The latest update, according to documents obtained by Radar Online: The billionaire filed a child custody suit in the fall after she allegedly flew to California with two of their kids 'and never returned.' In previous court filings, Grimes offered a different set of facts, claiming that it was Musk who left for Texas with one of their children without receiving her sign-off. She further alleged that Musk 'and his security team controlled nearly every aspect' of her life when the two spent time together.",
    "rights" => "© 2023 The Daily Beast Company LLC",
    "rank" => 634,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Noah Kirsch,Wealth,ter",
    "media" => "https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_2897,w_5152,x_0,y_0/dpr_2.0/c_limit,w_740/fl_lossy,q_auto/v1703873377/2023-12-29T010558Z_1035923379_RC2FK1A6FMZB_RTRMADP_3_CALIFORNIA-X-LAWSUIT-MUSK_apv0f2",
    "is_opinion" => false,
    "twitter_account" => "@thedailybeast",
    "_score" => 22.84667,
    "_id" => "02b5aad2648a5d1c54488cfe72302da5"
  ],
  [
    "title" => "Elon Musk dubbed 2023 ‘Scoundrel of the Year' by US website: ‘Evil, unserious'",
    "author" => "HT News Desk",
    "published_date" => "2023-12-29 10:08:46",
    "published_date_precision" => "full",
    "link" => "https://www.hindustantimes.com/business/elon-musk-dubbed-2023-scoundrel-of-the-year-by-us-website-evil-unserious-101703842084560.html",
    "clean_url" => "hindustantimes.com",
    "summary" => "Dec 29, 2023 03:38 PM IST \n \n \n \n \n \n \n \n \n \n \n \nTesla chief executive officer (CEO) Elon Musk has been dubbed as the ‘2023 Scoundrel of the Year' by American news website \nNew Republic\n. We are not joking. In a scathing article, the website has hit out at Musk, who also owns the social media platform X, formerly known as Twitter. Recalling the social media platform's move to suspend former US president Donald Trump's account in wake of the January 6 Capitol riots, the website said that X (then Twitter) is now ‘teetering on the brink of collapse' and is worth less than half of what Musk had paid to acquire it last year.",
    "rights" => "hindustantimes.com",
    "rank" => 980,
    "topic" => "news",
    "country" => "IN",
    "language" => "en",
    "authors" => "HT News Desk",
    "media" => "https://www.hindustantimes.com/ht-img/img/2023/12/29/1600x900/Elon_Musk_1703843746419_1703843746689.JPG",
    "is_opinion" => false,
    "twitter_account" => "@httweets",
    "_score" => 22.83971,
    "_id" => "1d4e3ed240ce06c6ce0ff74e1106109d"
  ],
  [
    "title" => "Elon Musk to Dogecoin creator: Portland is ‘terrible'",
    "author" => "John Ross Ferrara",
    "published_date" => "2023-12-28 22:48:47",
    "published_date_precision" => "full",
    "link" => "https://news.yahoo.com/elon-musk-dogecoin-creator-portland-224847753.html",
    "clean_url" => "yahoo.com",
    "summary" => "PORTLAND, Ore. (KOIN) — Tesla and SpaceX CEO Elon Musk and Dogecoin creator Billy Markus both shared their negative opinions of Portland on X this week, starting a lengthy discussion about the city on social media.\nThe conversation started on Dec. 26 when Markus wrote the following message on X:\n'What's something that used to be awesome but now is terrible? I'll start: Portland, Oregon.'\n\nMusk, who has been politically outspoken in recent months, agreed with Markus' assessment of Portland.\n'Yeah, what happened there?' Musk added.",
    "rights" => "yahoo.com",
    "rank" => 31,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "John Ross Ferrara",
    "media" => "https://media.zenfs.com/en/koin_articles_940/ca834cb25f59f8f5f68bd2dbe5842486",
    "is_opinion" => false,
    "twitter_account" => "@YahooNews",
    "_score" => 22.728243,
    "_id" => "2c9b4c94085c0a1b3c0b8d0bb28bba8c"
  ],
  [
    "title" => "Elon Musk is shaping up to be this generation's Henry Ford – for better or worse",
    "author" => "Nora Naughton",
    "published_date" => "2023-12-26 11:20:01",
    "published_date_precision" => "full",
    "link" => "https://www.businessinsider.com/elon-musk-henry-ford-21st-century-for-better-or-worse-2023-12",
    "clean_url" => "businessinsider.com",
    "summary" => "One hundred years after Henry Ford reshaped the automotive industry with the assembly line, Tesla CEO \nElon Musk\n is doing much the same for electric cars.\nMusk is a once-in-a-generation figure whose \nlegacy is becoming complicated\n in real time – not unlike the Ford founder who revolutionized vehicle production.\nMusk and \nFord\n have been compared to one another for several years now. Ford didn't invent the car, but he found a way to bring personal transportation to the masses. Similarly, Musk didn't invent EVs, but made them popular.",
    "rights" => "Insider Inc. 2023",
    "rank" => 106,
    "topic" => "business",
    "country" => "US",
    "language" => "en",
    "authors" => "Grace Kay,Nora Naughton",
    "media" => "https://i.insider.com/65849bec1c5c7b8c9a0b482e?width=1200&format=jpeg",
    "is_opinion" => false,
    "twitter_account" => "@CarsInsider",
    "_score" => 22.593334,
    "_id" => "52cf09b74377834090b4c566a6958efc"
  ],
  [
    "title" => "Here's how Elon Musk spent his Christmas reigniting his feud with Joe Biden",
    "author" => "Kwan Wei Kevin Tan",
    "published_date" => "2023-12-26 04:24:27",
    "published_date_precision" => "full",
    "link" => "https://www.yahoo.com/tech/heres-elon-musk-spent-christmas-042427861.html",
    "clean_url" => "yahoo.com",
    "summary" => "Elon Musk really doesn't like Joe Biden.\nMusk on Christmas Eve slammed the president for excluding Tesla from the White House EV summit in 2021.\nMusk has often brought up the incident whenever he criticizes Biden.\nIt looks like Joe Biden was very much on Elon Musk's mind this Christmas.\nThe Tesla CEO spent his Christmas holidays slamming the US president's treatment of his company.\n\"Let's not forget the White House giving Tesla the cold shoulder, excluding us from the EV summit and crediting GM with 'leading the electric car revolution' in the same quarter that they delivered 26 electric cars (not a typo) and Tesla delivered 300 thousand,\" Musk wrote on X on Sunday.",
    "rights" => "yahoo.com",
    "rank" => 31,
    "topic" => "tech",
    "country" => "US",
    "language" => "en",
    "authors" => "Kwan Wei Kevin Tan",
    "media" => "https://media.zenfs.com/en/business_insider_articles_888/8a10584383fa490c0456494ad2cc0845",
    "is_opinion" => false,
    "twitter_account" => "@Yahoo",
    "_score" => 22.547678,
    "_id" => "6a3f467706988b30fa3355a8227a5079"
  ],
  [
    "title" => "This Is How Elon Musk Got Rich",
    "author" => "Pm Est",
    "published_date" => "2023-12-28 18:32:00",
    "published_date_precision" => "timezone unknown",
    "link" => "https://www.nasdaq.com/articles/this-is-how-elon-musk-got-rich",
    "clean_url" => "nasdaq.com",
    "summary" => "Have you ever wondered how industry giants like Elon Musk and Mark Cuban built their empires?\n\nThese industry leaders dominate headlines with their vast fortunes, yet the way they came into their riches might surprise you.\n\nLet's start with Musk.\n\nMost people think Musk's wealth stems from Tesla (TSLA). As the CEO of the electric vehicle (EV) company, it's no secret that TSLA has been a rocket ship for Musk's net worth, with an astonishing 3,000% stock surge over the last decade.\n\nBut Musk's journey to wealth began long before his tenure as Tesla's chief executive…\n\nWhat's the real story behind Musk's billions?\n\nThe Secret to Elon Musk's Fortune\n\nIt's a tale of strategic foresight during the Dot-Com Boom, where a unique and rare investment vehicle turned into a goldmine for those who knew where to look.",
    "rights" => "nasdaq.com",
    "rank" => 713,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "InvestorPlace,Luke Lango,Pm Est",
    "media" => "https://www.nasdaq.com/sites/acquia.prod/files/2019-05/0902-Q19%20Total%20Markets%20photos%20and%20gif_CC8.jpg",
    "is_opinion" => false,
    "twitter_account" => "@Nasdaq",
    "_score" => 22.272247,
    "_id" => "9f955fbfd39c37d7a9bb3b87965b4787"
  ],
  [
    "title" => "Elon Musk's X Loses Bid To Change California Content Moderation Law",
    "author" => "Bruce Haring",
    "published_date" => "2023-12-29 02:56:19",
    "published_date_precision" => "full",
    "link" => "https://deadline.com/2023/12/elon-musk-x-loses-bid-change-california-content-moderation-law-1235683053/",
    "clean_url" => "deadline.com",
    "summary" => "Elon Musk \n\n\nMichael M. Santiago/Getty Images\n\n\n\n\n\n\n\n\n\n\nElon Musk\n‘s X on Thursday has lost its bid to change a \nCalifornia\n law on content moderation disclosure by social media companies.\n\n\n\n\tX sued California in September to undo the state's content moderation law, saying it violated free speech rights under the U.S. Constitution's First Amendment and California's state constitution.\n\n\n\n\tToday, U.S. District Judge William Shubb dismissed the social media company's request in an eight-page decision .",
    "rights" => "deadline.com",
    "rank" => 921,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Bruce Haring",
    "media" => "https://deadline.com/wp-content/uploads/2023/11/Elon-Musk-DealBook.jpg?w=1024",
    "is_opinion" => false,
    "twitter_account" => "@Deadline",
    "_score" => 22.207123,
    "_id" => "ee4e0d7805f1d60aa52b4bc51e34e410"
  ],
  [
    "title" => "Elon Musk Made 2023 All About Himself",
    "author" => "Max Chafkin",
    "published_date" => "2023-12-26 21:20:11",
    "published_date_precision" => "full",
    "link" => "https://www.bloomberg.com/news/articles/2023-12-26/podcast-elon-musk-made-2023-all-about-himself",
    "clean_url" => "bloomberg.com",
    "summary" => "On this episode of Elon, Inc., we talk to PJ Vogt of the Search Engine podcast about what the billionaire's tumultuous year means for the next one.\n\nBy\n\nSave\n\nListen and subscribe to Elon, Inc. on Apple, Spotify, iHeart and the Bloomberg Terminal.",
    "rights" => "bloomberg.com",
    "rank" => 92,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Max Chafkin",
    "media" => "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/i2J8CcWUlA50/v0/1200x800.jpg",
    "is_opinion" => false,
    "twitter_account" => "@BW",
    "_score" => 22.201092,
    "_id" => "179af71144e175bb029ed9b28bc028d2"
  ],
  [
    "title" => "‘Elon Musk looking at Gujarat as first choice for Tesla factory', says state minister",
    "author" => "PTI",
    "published_date" => "2023-12-30 07:03:06",
    "published_date_precision" => "full",
    "link" => "https://www.hindustantimes.com/business/elon-musk-looking-at-gujarat-as-first-choice-for-tesla-factory-says-state-minister-101703919256903.html",
    "clean_url" => "hindustantimes.com",
    "summary" => "Gujarat minister Rushikesh Patel on Thursday said his government was \"very hopeful\" that Elon Musk-led Tesla will choose the state to set up a plant and informed communication was on with the firm in this regard. A Tesla logo is seen outside a showroom of the carmaker in Beijing, China.(REUTERS)\n\nPatel was responding to queries based on news reports suggesting that the US-based electric vehicle maker was planning to set up a manufacturing plant in Gujarat.\n\nWrap up the year gone by & gear up for 2024 with HT! Click here\n\n\"The state government is very hopeful of Tesla coming to Gujarat.",
    "rights" => "hindustantimes.com",
    "rank" => 980,
    "topic" => "news",
    "country" => "IN",
    "language" => "en",
    "authors" => "PTI",
    "media" => "https://www.hindustantimes.com/ht-img/img/2023/12/30/1600x900/TESLA-CHINA--0_1703919287963_1703919313195.JPG",
    "is_opinion" => false,
    "twitter_account" => "@httweets",
    "_score" => 22.122568,
    "_id" => "276d21c34463983900d305fa6851a0c7"
  ],
  [
    "title" => "Tesla: Is Elon Musk too distracted by his other companies?",
    "author" => "Brad Smith",
    "published_date" => "2023-12-28 15:49:58",
    "published_date_precision" => "full",
    "link" => "https://finance.yahoo.com/video/tesla-elon-musk-too-distracted-154958602.html",
    "clean_url" => "yahoo.com",
    "summary" => "Tesla (TSLA) investors have been increasingly anxious about CEO Elon Musk's focus on the EV maker while juggling his various other projects and companies, including X, SpaceX, and the Boring Company. Yahoo Finance Live examines potential distractions for Musk and whether these priorities could weigh down Tesla's stock and its EV production goals heading into 2024.\nFor more expert insight and the latest market action, click here to watch this full episode of Yahoo Finance Live.\nBRAD SMITH: Year 2023 has been a rocky year for Tesla and CEO Elon Musk.",
    "rights" => "yahoo.com",
    "rank" => 31,
    "topic" => "news",
    "country" => "US",
    "language" => "en",
    "authors" => "Brad Smith,Luke Carberry Mogan",
    "media" => "https://s.yimg.com/ny/api/res/1.2/M1lpqGU9dkIDil1RZn.iTQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzY-/https://s.yimg.com/os/creatr-uploaded-images/2023-12/b2bc7010-a598-11ee-b986-c788ab943823",
    "is_opinion" => false,
    "twitter_account" => "@thebradsmith",
    "_score" => 22.09956,
    "_id" => "26eb2da92487cb0676d23b141c507141"
  ]
];

